# Generated by Django 5.1.2 on 2024-10-23 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishments',
            name='formation',
        ),
        migrations.AddField(
            model_name='formations',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parcoursup.establishments'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
